### ISSUE TITLE
语言朗读时报错：Reference to undeclared entity'nbsp'.Line 1,position 252

### ISSUE THREAD

**Issue by DesignerXY** [read-cat/read-cat#13]
使用系统默认语音朗读时，报错如下图所示：
![20240611_162003_990_copy](https://github.com/read-cat/read-cat/assets/17871216/a5ec870d-c698-4196-8836-e2eabe860fae)

**Comment by moomewa** [comment]
发下书源、书名、作者、哪一章节、TTS引擎。还有日志（设置/关于/导出日志）

**Comment by moomewa** [comment]
已修复 c280c1d25afc4b0f6a91c9449158aed3175491cb
