### ISSUE TITLE
番茄小说源异常

### ISSUE THREAD

**Issue by Yuuki-Rin** [read-cat/read-cat#4]
番茄小说源并搜不到番茄的小说

**Comment by dmyz** [comment]
这是个debug，不能启用多个书源；如果有多个书源，只保留番茄小说书源，其他禁用

**Comment by Yuuki-Rin** [comment]
> 这是个debug，不能启用多个书源；如果有多个书源，只保留番茄小说书源，其他禁用

就单纯搜不到我要看的小说
番茄的

**Comment by dmyz** [comment]
@Yuuki-Rin 那就没这小说，换别的书源找找
