### ISSUE TITLE
导入插件出错

### ISSUE THREAD

**Issue by 9o8i7u** [read-cat/read-cat#5]
版本：1.0.0-dev.240503
导入网站下载的插件，提示：
The user aborted a request.

**Comment by baird19** [comment]
我的也是，有bug

**Comment by moomewa** [comment]
> 版本：1.0.0-dev.240503 导入网站下载的插件，提示： The user aborted a request.

导入插件提示The user aborted a request.，将插件文件移动到非系统盘目录下或桌面再次导入即可

**Comment by 9o8i7u** [comment]
> > 版本：1.0.0-dev.240503 导入网站下载的插件，提示： The user aborted a request.
> 
> 导入插件提示The user aborted a request.，将插件文件移动到非系统盘目录下或桌面再次导入即可

程序在非系统盘，程序目录非中文；没有空格，
插件在程序目录下建2级目录，非中文没空格。
一样The user aborted a request.
用管理员身份一样。

另，网站read-cat.github.io 5月5日可以打开，今天read-cat.github.io和read-cat.top打不开了，提示重定向过多，edge,firefox,chrome都一样。

**Comment by moomewa** [comment]
> > > 版本：1.0.0-dev.240503 导入网站下载的插件，提示： The user aborted a request.
> > 
> > 
> > 导入插件提示The user aborted a request.，将插件文件移动到非系统盘目录下或桌面再次导入即可
> 
> 程序在非系统盘，程序目录非中文；没有空格， 插件在程序目录下建2级目录，非中文没空格。 一样The user aborted a request. 用管理员身份一样。
> 
> 另，网站read-cat.github.io 5月5日可以打开，今天read-cat.github.io和read-cat.top打不开了，提示重定向过多，edge,firefox,chrome都一样。

不要将插件文件放在程序安装目录及子目录下
