### ISSUE TITLE
多个书源不能一起使用，保留一个书源，其他禁用，就可以正常使用

### ISSUE THREAD

**Issue by dmyz** [read-cat/read-cat#7]
保留一个使用正常
![图片](https://github.com/read-cat/read-cat/assets/15307200/df7f4869-ab75-4605-a746-fb320b314523)
![图片](https://github.com/read-cat/read-cat/assets/15307200/639d6d09-32ed-475f-b1d9-16bb16ce16c0)

多个启用不能用
![图片](https://github.com/read-cat/read-cat/assets/15307200/393b5f34-292a-42a3-b66f-44758514c6e8)
![图片](https://github.com/read-cat/read-cat/assets/15307200/c8e3dea7-122c-42ea-bd4a-392400037062)

**Comment by moomewa** [comment]
> 保留一个使用正常 ![图片](https://private-user-images.githubusercontent.com/15307200/328098900-df7f4869-ab75-4605-a746-fb320b314523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzkwNjAsIm5iZiI6MTcxNDk3ODc2MCwicGF0aCI6Ii8xNTMwNzIwMC8zMjgwOTg5MDAtZGY3ZjQ4NjktYWI3NS00NjA1LWE3NDYtZmIzMjBiMzE0NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA2NTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZGE3YTVkZGUyOTcxYzI2MzUyOWVmZjc0YzlmZTRkMGQwY2EwZGJjODA4N2Y1NDE4YWEzYWQ4NWNmMTA3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4hIQRKwV-thp3q9iOpugX_Sfaf-nPYDZs5U5EbJb6M) ![图片](https://private-user-images.githubusercontent.com/15307200/328098709-639d6d09-32ed-475f-b1d9-16bb16ce16c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzkwNjAsIm5iZiI6MTcxNDk3ODc2MCwicGF0aCI6Ii8xNTMwNzIwMC8zMjgwOTg3MDktNjM5ZDZkMDktMzJlZC00NzVmLWIxZDktMTZiYjE2Y2UxNmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA2NTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MzY2MGE5ODU5MmIzZTQ3MjU0MWE0ZTRhNDY1YjIwNDViNTM5OGZjOThiOTg0ZTQ0ZTZjMDM3Y2RkMzdhMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZVdlzr6Zz2ezMFZ2jbrl-ZUQnjo9Dh0rrpClHY8Rek)
> 
> 多个启用不能用 ![图片](https://private-user-images.githubusercontent.com/15307200/328098843-393b5f34-292a-42a3-b66f-44758514c6e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzkwNjAsIm5iZiI6MTcxNDk3ODc2MCwicGF0aCI6Ii8xNTMwNzIwMC8zMjgwOTg4NDMtMzkzYjVmMzQtMjkyYS00MmEzLWI2NmYtNDQ3NTg1MTRjNmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA2NTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NDhiNmNkODMzNTFmMzZjZjc3ZjcwNTNmMGE3NDliMmRjZDQzZTg0NDlhODY5MmI2YjIyZGY4ZmZmZjc4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HC3nIh-8SQjmXx3_SSiinoZAhFMcHdfoURkWAY97Jxo) ![图片](https://private-user-images.githubusercontent.com/15307200/328098873-c8e3dea7-122c-42ea-bd4a-392400037062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzkwNjAsIm5iZiI6MTcxNDk3ODc2MCwicGF0aCI6Ii8xNTMwNzIwMC8zMjgwOTg4NzMtYzhlM2RlYTctMTIyYy00MmVhLWJkNGEtMzkyNDAwMDM3MDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA2NTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YzNjZTdmMTJjNjFjNTQ1YTcyZmFiMDBiNTE5MGNiNzhmNzdmYTU1MDNkMGNmODk4ZDU0Njc4ZDA0NmUzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j5HF-lVwgsVoENOb4kn4U-Zr-zyGu1wD1T4USgvCk0w)

状态显示启用代表插件是启用的，显示禁用插件就是禁用状态自然没有搜索结果

**Comment by githubhc20** [comment]
虽然题主问的这个问题确实让人有点难绷。。。不过如果做成那种拨动开关形式的会更直观些
