### ISSUE TITLE
翻页之后，需要鼠标点击一下页面才能继续用键盘下键滚动页面

### ISSUE THREAD

**Issue by githubhc20** [read-cat/read-cat#8]
翻页之后，需要鼠标点击一下页面才能继续用键盘下键滚动页面

**Comment by githubhc20** [comment]
是用键盘右键翻页后，需要鼠标点击一下页面才能继续用键盘下键滚动页面

**Comment by moomewa** [comment]
> 翻页之后，需要鼠标点击一下页面才能继续用键盘下键滚动页面

下载最新版，增加了向上/下滚动快捷键，其他快捷键屏蔽了（除了设置/快捷键）

**Comment by githubhc20** [comment]
> > 翻页之后，需要鼠标点击一下页面才能继续用键盘下键滚动页面
> 
> 下载最新版，增加了向上/下滚动快捷键，其他快捷键屏蔽了（除了设置/快捷键）

刚才安装了5月8日版本，似乎的确解决了这个问题，不过这个版本长按向下键盘似乎并不能连续平滑地滚动，要一下下地按键盘，页面显示也是一跳一跳地往下滚动，不顺滑。

**Comment by moomewa** [comment]
> 可以更改阅读形式，阅读时我习惯使用鼠标滑动，滑倒底部希望能自动加载下一章，不用额外再去按键盘，这或许更符合阅读习惯

已在 fece50bbec644ae7a67caf197052a96340309a70 解决
