### ISSUE TITLE
[Bug]: 不支持模糊搜索，不能缓存章节

### ISSUE THREAD

**Issue by sunjunps** [read-cat/read-cat#9]
### 问题描述

搜索全名时可以搜到书，搜索部分字比如重生，穿越等就没有结果
另外如果能缓存章节到本地就更好了

### 复现

直接搜索书名的部分字

### 版本号

1.0.0-dev.240510

### 提交

df1576dba17dc05dbe3ef7c37cc04d2b3735aa2d

### 日志

无需

**Comment by moomewa** [comment]
搜索结果跟书源有关系，ReadCat只过滤搜索结果中书名及作者不包含搜索关键词的书本
ReadCat是支持章节缓存的，但不支持将缓存导出至文件
